# Generated by Django 2.2.2 on 2019-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='open_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('current_address', models.CharField(max_length=150)),
                ('aadhar', models.CharField(max_length=150)),
                ('pan', models.CharField(max_length=150)),
                ('relative', models.CharField(max_length=150)),
            ],
        ),
    ]
