# Generated by Django 2.2.2 on 2019-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190725_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_account',
            name='id',
        ),
        migrations.AlterField(
            model_name='open_account',
            name='mobile',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
