# Generated by Django 2.2.2 on 2019-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_fd'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_loan',
            fields=[
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('repay', models.CharField(max_length=10)),
                ('approved', models.CharField(max_length=10)),
            ],
        ),
    ]
