# Generated by Django 2.2.2 on 2019-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('kind', models.CharField(max_length=150)),
                ('account', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
